# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b955019fab6b56a93528bf0aa75043ff767c1c47d257a0f5594371ed86d8379b7a6909084b057e837041d93bd95a52275c505e18150150b5ff4414776676407c

test:
  secret_key_base: 86eae0d038297dd6242d7d42318c1e831c09235b939bfb91252f428586f3f5bcdbd9aa8e18f9b7153b8f2ed24a38f28259a5689850ffd0b434f67c96286b1090

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
